# Generated by Django 4.1 on 2022-08-15 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese nombre del director', max_length=30)),
                ('apellido', models.CharField(help_text='Ingrese apellido del director', max_length=30)),
                ('day_birth', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese aquí el nombre de género', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingrese nombre de la película', max_length=150)),
                ('sinopsis', models.TextField(help_text='Ingrese aquí su sinopsis', max_length=1000)),
                ('isbn', models.CharField(help_text='El ISBN de 13 caracteres', max_length=13, verbose_name='ISBN')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directores.directores')),
                ('genre', models.ManyToManyField(to='directores.genre')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculasInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f0567721-57db-42c3-a7d4-6c42d63ba584'), help_text='Id unico para esta película', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('s', 'Serie'), ('p', 'Película'), ('c', 'Cortometraje'), ('d', 'Documental'), ('m', 'Miniserie')], default='p', help_text='Tipo de película', max_length=1)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directores.peliculas')),
            ],
            options={
                'ordering': ['pelicula'],
            },
        ),
    ]
